---
    name: "tagged-prerelease"
    
    on:
      push:
        tags:
          - "v*"
    
    jobs:
      tagged-release:
        name: "Tagged Pre-release"
        runs-on: "ubuntu-latest"
    
        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK
              uses: joschi/setup-jdk@v2
              with:
                java-version: '8'
            - name: Build with Maven
              run: mvn -B package --file pom.xml
            - uses: "marvinpinto/action-automatic-releases@<VERSION>"
                with:
                repo_token: "${{ secrets.GITHUB_TOKEN }}"
                prerelease: true
                files: |
                    LICENSE
                    target/*.jar